### PR TITLE
Fix...

### PR DESCRIPTION
**Pull request by GabBiswajit**
I Don't Test....
Now You Can Update What You Want By Your Self..
Voting38 Is Default Requirement To Run This Plugin....

### CODE REVIEW

**Comment by GabBiswajit** [comment]
@antbag-dev die?

**Comment by antbag-dev** [comment]
It wasnt made compulsory due to a reason being so that players could either take the api key from the vote web and use it here. Another options is that there is a development of new vote plugin which was stopped few days back but it would be available to poggit soon and i think most of the people would love it

**Comment by antbag-dev** [comment]
> @antbag-dev die?

Are you impatient or what

**Comment by GabBiswajit** [comment]
Hmm for now you can fix the bugs...

**Comment by antbag-dev** [comment]
> Hmm for now you can fix the bugs...

Done Thanks for Highlighting the issue

**Pull request closed without merging**
